DEVOPS-160 Refactoring workflows in a main one

diff --git a/.github/workflows/deploy-service.yml b/.github/workflows/deploy-service.yml
--- a/.github/workflows/deploy-service.yml
+++ b/.github/workflows/deploy-service.yml
@@ -20,30 +20,60 @@ on:
         required: false
         type: string
         default: null
+      JIRA_CODE:
+        required: false
+        type: string
+        default: ''
       # FORCE_DEPLOYMENT is not bool because output transforms it in text
       FORCE_DEPLOYMENT:
-        required: true
+        required: false
         type: string
+        default: 'false'
       DNS_PREFIX:
         required: false
         type: string
         default: null
+      NOTIFICATIONS_TEAMS:  # booleans must be treated as string
+        required: false
+        type: string
+        default: 'true'
+      NOTIFICATIONS_JIRA:
+        required: false
+        type: string
+        default: 'true'
     secrets:
       AWS_ACCESS_KEY_ID_TF:
         required: true
       AWS_SECRET_ACCESS_KEY_TF:
         required: true
-      GH_TF_SSH_KEY_JULIEN_LEDOUX:
+      GH_TF_SSH_KEY:
         required: true
+      MS_TEAMS_WEBHOOK_URI:
+        required: true
+      JIRA_USER_EMAIL:
+        required: true
+      JIRA_API_TOKEN:
+        required: true
+    # Map the workflow outputs to job outputs
+    outputs:
+      DEPLOY_STATUS:
+        description: "DEPLOY_STATUS might be: error, failure, success"
+        value: ${{ jobs.monitor-deployment.outputs.DEPLOY_STATUS }}
 
 concurrency:
   group: ${{ github.workflow }}-${{ inputs.CLUSTER }}
   cancel-in-progress: false
 
 jobs:
-  deploy-service:
-    name: Terraform deploy service '${{ matrix.service }}' on cluster '${{ inputs.CLUSTER }}'
+  tf-service:
+    name: Tf '${{ matrix.service }}' on cluster '${{ inputs.CLUSTER }}'
     runs-on: [self-hosted, "${{ inputs.CLUSTER }}"]
+    timeout-minutes: 20
+
+    # For deployment-action and checkout
+    permissions:
+      contents: read
+      deployments: write
 
     strategy:
       matrix:
@@ -69,10 +99,6 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}
           aws-region: ${{ inputs.AWS_DEFAULT_REGION }}
 
-      # - uses: actions/setup-node@v2
-      #   with:
-      #     node-version: '14'
-
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
@@ -81,7 +107,7 @@ jobs:
 
       - name: Terraform init service '${{ matrix.service }}' on cluster '${{ inputs.CLUSTER }}' configuration
         env:
-          GIT_SSH_COMMAND: "echo '${{ secrets.GH_TF_SSH_KEY_JULIEN_LEDOUX }}' > id_rsa
+          GIT_SSH_COMMAND: "echo '${{ secrets.GH_TF_SSH_KEY }}' > id_rsa
             && ssh-keyscan github.com > known_hosts
             && chmod 600 id_rsa known_hosts
             && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
@@ -97,6 +123,7 @@ jobs:
           terraform validate -no-color
 
       - name: Terraform apply service '${{ matrix.service }}' on cluster '${{ inputs.CLUSTER }}'
+        id: tf-apply-service
         working-directory: ./.terraform/services
         run: |
           cd ${{ matrix.service }}
@@ -129,3 +156,80 @@ jobs:
             -var "image_tag=${DOCKER_IMAGE_TAG}" \
             -var "use_bastion_ssh_tunnel=false" \
             ${FORCE_DEPLOY_PARAM}
+
+      #--------------------------------------------------------
+
+      # Checkout reusable workflow to get bash scripts
+      - uses: actions/checkout@v3
+        with:
+          repository: Sonergia/github-reusable-workflows
+          ref: 'delivery' # Only when testing ############## /!\ ##############
+
+      - name: Monitor deployment
+        id: monitor-deployment
+        # if: ${{ steps.tf-apply-service.conclusion != 'failure' }}
+        run: ./.github/scripts/monitor-deployment.sh ${{ inputs.CLUSTER }} ${{ matrix.service }}
+
+      - name: Check deploy status
+        id: check-deploy-status
+        if: always()
+        run: |
+          DEPLOY_STATUS=${{ steps.monitor-deployment.outputs.DEPLOY_STATUS }}
+
+          if [ -z "${DEPLOY_STATUS}" ]; then
+            DEPLOY_STATUS=error
+          fi
+
+          echo "::set-output name=DEPLOY_STATUS::${DEPLOY_STATUS}"
+
+      - name: Map vars with github environment
+        id: map-github-env
+        if: always()
+        run: |
+          # Available env: development, testing, staging, or production
+          GITHUB_ENVIRONMENT=${{ inputs.CLUSTER }}
+
+          if [ "${{ inputs.CLUSTER }}" == "release" ]; then
+            GITHUB_ENVIRONMENT="staging"
+          fi
+
+          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
+
+          echo "::set-output name=GITHUB_ENVIRONMENT::${GITHUB_ENVIRONMENT}"
+          echo "::set-output name=COMMIT_MESSAGE::${COMMIT_MESSAGE}"
+
+      - name: Change string case function
+        id: string
+        uses: ASzc/change-string-case-action@v2
+        if: always()
+        with:
+          string: ${{ inputs.CLUSTER }}
+
+      - name: Create GitHub deployment
+        id: github-deployment
+        uses: chrnorm/deployment-action@v2
+        if: ${{ always() && inputs.NOTIFICATIONS_JIRA == 'true' }}
+        with:
+          token: ${{ github.token }}
+          # error, failure, in_progress, queued, pending, success, (inactive)
+          initial-status: ${{ steps.map-github-env.outputs.DEPLOY_STATUS }}
+          auto-inactive: false
+          task: deploy-${{ inputs.CLUSTER }}-${{ inputs.IMAGE_SHA }}
+          # Use log-url since JIRA does not display environment-url
+          # environment-url: http://${{ matrix.service }}.${{ inputs.CLUSTER }}.ecs
+          log-url: http://${{ matrix.service }}.${{ inputs.CLUSTER }}.ecs
+          # log-url: https://app.datadoghq.eu/logs?query=service:cloudwatch%20cluster:${{ inputs.CLUSTER }}%20%40service:${{ matrix.service }}
+          environment: ${{ steps.map-github-env.outputs.GITHUB_ENVIRONMENT }}
+          # Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future.
+          transient-environment: ${{ inputs.CLUSTER != 'prod' }}
+          description: ${{ matrix.service }} (${{ inputs.IMAGE_SHA }} / ${{ inputs.IMAGE_TAG }}) deployed on cluster ${{ inputs.CLUSTER }}
+
+      - name: Exit if deploy failed
+        run: |
+          DEPLOY_STATUS=${{ steps.check-deploy-status.outputs.DEPLOY_STATUS }}
+          if [ ${DEPLOY_STATUS} != 'success' ]; then
+            exit 1
+          fi
+
+    outputs:
+      DEPLOY_STATUS: ${{ steps.check-deploy-status.outputs.DEPLOY_STATUS }}
